root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/"
bin = "./tmp/main"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "tests"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_regex = ["_test\\.go"]

[log]
time = false

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
